import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata = { title: "Company" };

export default function CompanyPage() {
  return <><SiteHeader /><main id="main"><section className="content-hero section-dark"><div className="container"><p className="eyebrow dark">COMPANY</p><h1>Evidence before claims.</h1><p>This page is structured for approved THROHI company information without inventing age, reach, certifications, factory scale, or manufacturing capabilities.</p></div></section><section className="section"><div className="container content-grid"><article><p className="eyebrow">APPROVED FOUNDATION</p><h2>What can be stated now</h2><p>THROHI Medical Tools presents surgical, dental, veterinary, and beauty instrument catalogues through a structured B2B inquiry platform.</p></article><aside className="verification-panel"><h3>Pending verification</h3><ul><li>Legal company description</li><li>Full registered address and contact details</li><li>Manufacturing and quality-control evidence</li><li>Certifications and catalogue claims</li><li>OEM or private-label availability</li><li>Export and market information</li></ul></aside></div></section><section className="section evidence-section"><div className="container"><div className="section-heading"><p className="eyebrow">PUBLICATION RULE</p><h2>Unsupported proof blocks remain unpublished.</h2></div><div className="evidence-list"><span>Company identity · pending approval</span><span>Location · pending approval</span><span>Capabilities · excluded until verified</span><span>Quality evidence · excluded until verified</span></div></div></section><section className="final-cta section-dark"><div className="container final-grid"><div><h2>Evaluate the product catalogue.</h2><p>Browse instrument families or send a structured request with the products you need.</p></div><div className="button-row"><Link className="button inverse-light" href="/products">Browse products</Link><Link className="button primary" href="/inquiry">Build inquiry</Link></div></div></section></main><SiteFooter /></>;
}
