import type { Product } from "@/lib/catalogue";

export type ScissorsPreviewProduct = Product & { imagePath: string };

const description = "Catalogue image review record. Product facts and publication approval remain pending.";
const approvalNotes = "Image preview only. Identity remains pending final visual approval.";

export const scissorsPreviewProducts: readonly ScissorsPreviewProduct[] = [
  { id: "preview-scissors-iris-regular", slug: "iris-scissors-regular", code: "04-0800", name: "Iris Scissors", division: "surgical", family: "scissors", description, aliases: ["iris scissors", "regular iris scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-iris-regular.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-iris-super-cut", slug: "iris-scissors-super-cut", code: "05-0802", name: "Iris Scissors — Super Cut", division: "surgical", family: "scissors", description, aliases: ["iris scissors", "super cut iris scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-iris-super-cut.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-iris-tc", slug: "iris-scissors-tc", code: "06-0802", name: "Iris Scissors — TC", division: "surgical", family: "scissors", description, aliases: ["iris scissors", "tc iris scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-iris-tc.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-stevens-regular", slug: "stevens-scissors-regular", code: "04-0901", name: "Stevens Tenotomy Scissors", division: "surgical", family: "scissors", description, aliases: ["stevens scissors", "tenotomy scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-stevens-regular.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-stevens-super-cut", slug: "stevens-scissors-super-cut", code: "05-0901", name: "Stevens Tenotomy Scissors — Super Cut", division: "surgical", family: "scissors", description, aliases: ["stevens scissors", "super cut tenotomy scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-stevens-super-cut.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-stevens-tc", slug: "stevens-scissors-tc", code: "06-0901", name: "Stevens Tenotomy Scissors — TC", division: "surgical", family: "scissors", description, aliases: ["stevens scissors", "tc tenotomy scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-stevens-tc.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-operating-regular", slug: "operating-scissors-regular", code: "04-0101", name: "Operating Scissors", division: "surgical", family: "scissors", description, aliases: ["operating scissors", "regular operating scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-operating-regular.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-operating-super-cut", slug: "operating-scissors-super-cut", code: "05-0101", name: "Operating Scissors — Super Cut", division: "surgical", family: "scissors", description, aliases: ["operating scissors", "super cut operating scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-operating-super-cut.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-operating-tc", slug: "operating-scissors-tc", code: "06-0101", name: "Operating Scissors — TC", division: "surgical", family: "scissors", description, aliases: ["operating scissors", "tc operating scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-operating-tc.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-mayo-regular", slug: "mayo-scissors-regular", code: "04-0401", name: "Mayo Scissors", division: "surgical", family: "scissors", description, aliases: ["mayo scissors", "regular mayo scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-mayo-regular.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-mayo-super-cut", slug: "mayo-scissors-super-cut", code: "05-0401", name: "Mayo Scissors — Super Cut", division: "surgical", family: "scissors", description, aliases: ["mayo scissors", "super cut mayo scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-mayo-super-cut.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-mayo-tc", slug: "mayo-scissors-tc", code: "06-0401", name: "Mayo Scissors — TC", division: "surgical", family: "scissors", description, aliases: ["mayo scissors", "tc mayo scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-mayo-tc.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-metzenbaum-regular", slug: "metzenbaum-scissors-regular", code: "04-1901", name: "Metzenbaum Scissors", division: "surgical", family: "scissors", description, aliases: ["metzenbaum scissors", "regular metzenbaum scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-metzenbaum-regular.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-metzenbaum-super-cut", slug: "metzenbaum-scissors-super-cut", code: "05-1901", name: "Metzenbaum Scissors — Super Cut", division: "surgical", family: "scissors", description, aliases: ["metzenbaum scissors", "super cut metzenbaum scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-metzenbaum-super-cut.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes },
  { id: "preview-scissors-metzenbaum-tc", slug: "metzenbaum-scissors-tc", code: "06-1901", name: "Metzenbaum Scissors — TC", division: "surgical", family: "scissors", description, aliases: ["metzenbaum scissors", "tc metzenbaum scissors"], status: "draft", imageState: "available", imagePath: "/media/scissors-preview/scissors-metzenbaum-tc.svg", variants: [], specifications: [], documents: [], relatedProductIds: [], updatedAt: "2026-08-02", approvalNotes }
] as const;

export function getScissorsPreviewProduct(slug: string) {
  return scissorsPreviewProducts.find(product => product.slug === slug);
}
