import Link from "next/link";
import { ProductCard } from "@/components/catalogue-ui";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { catalogueCounts, divisions, families, products } from "@/lib/catalogue";

export const metadata = { title: "Instrument Catalogue" };

const featuredProducts = divisions.flatMap(division => products.filter(product => product.division === division.slug).slice(0, 2));

export default function ProductsPage() {
  return <><SiteHeader /><main id="main" className="catalogue-v2 catalogue-hub">
    <section className="catalogue-hub-hero"><div className="container catalogue-hub-grid"><div className="catalogue-hub-copy"><p className="eyebrow dark">COMPLETE INSTRUMENT CATALOGUE</p><h1>Two catalogues.<br /><span>{catalogueCounts.variants.toLocaleString()} documented variants.</span></h1><p>Browse General Surgery and Orthodontic Instruments by catalogue, family, representative product group, exact variant code, or working description.</p><div className="catalogue-hub-stats"><span><b>{catalogueCounts.divisions}</b>Catalogues</span><span><b>{catalogueCounts.families}</b>Families</span><span><b>{catalogueCounts.products}</b>Instrument groups</span><span><b>{catalogueCounts.variants.toLocaleString()}</b>Variants</span></div></div><form className="catalogue-command" action="/search"><header><span>CATALOGUE COMMAND</span><small>CODE · NAME · FAMILY · VARIANT</small></header><label htmlFor="catalogue-command-query">Search all documented instruments</label><div className="catalogue-command-field"><input id="catalogue-command-query" name="q" type="search" placeholder="Try SC-01T, scissors, forceps, aligner…" /><button type="submit">SEARCH ↗</button></div><Link className="manual-recovery-link" href="/inquiry?manual=1"><span>Cannot locate a reference?</span><strong>Add an unlisted item</strong><b aria-hidden="true">+</b></Link></form></div></section>

    <section className="catalogue-division-index" aria-labelledby="catalogue-divisions-title"><div className="container"><header className="catalogue-section-heading"><div><p className="eyebrow">CATALOGUE ROUTES</p><h2 id="catalogue-divisions-title">Begin with the supplied catalogue.</h2></div><p>Each route exposes its complete family structure, representative images, variant descriptions, source pages, search, and inquiry controls.</p></header></div><div className="catalogue-division-rows">{divisions.map(division => <Link className={`catalogue-division-row tone-${division.slug}`} href={`/products/${division.slug}`} key={division.slug}><span className="division-row-index">{division.index}</span><span className="division-row-title"><strong>{division.label}</strong><small>{division.productCount} GROUPS · {division.variantCount} VARIANTS</small></span><p>{division.description}</p><span className="division-row-family-count">{division.familySlugs.length} families</span><b aria-hidden="true">↗</b></Link>)}</div></section>

    <section className="catalogue-family-index" aria-labelledby="family-index-title"><div className="container catalogue-family-index-grid"><aside className="catalogue-family-index-intro"><p className="eyebrow">ALL FAMILIES</p><h2 id="family-index-title">{catalogueCounts.families} organized instrument families.</h2><p>Size-only variants are consolidated under representative groups. Functionally or geometrically distinct instruments remain separate.</p><Link href="/search">Search the complete catalogue ↗</Link></aside><nav className="catalogue-family-routes" aria-label="All catalogue families">{families.map(family => <Link href={`/products/${family.division}/${family.slug}`} key={`${family.division}-${family.slug}`}><span>{family.index}</span><div><strong>{family.label}</strong><small>{family.productCount} groups · {family.variantCount} variants</small></div><b aria-hidden="true">↗</b></Link>)}</nav></div></section>

    <section className="catalogue-featured-objects" aria-labelledby="featured-catalogue-title"><div className="container"><header className="catalogue-section-heading"><div><p className="eyebrow">REPRESENTATIVE OBJECTS</p><h2 id="featured-catalogue-title">A first view into both catalogues.</h2></div><Link className="catalogue-heading-link" href="/search">Open full search ↗</Link></header><div className="catalogue-editorial-grid">{featuredProducts.map(product => <ProductCard product={product} key={product.id} />)}</div></div></section>

    <section className="catalogue-recovery-band"><div className="container"><span className="recovery-code">SOURCE-LED CATALOGUE</span><div><h2>Every object keeps its source variants.</h2><p>Open a product group to review exact codes, descriptions, dimensions, material or finish notes, and source-page references.</p></div><Link className="primary-recovery" href="/inquiry">Review inquiry ↗</Link></div></section>
  </main><SiteFooter /></>;
}
